In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
# %%capture --no-stderr
# !pip install python-dotenv openAI langchain_core langchain_openai langchain langchain-community sentence_transformers rank_bm25

In [3]:
# <오픈AI 임베딩을 활용한 벡터들 간 코사인 유사도 계산>

# 라이브러리 불러오기
import os
from dotenv import load_dotenv
import numpy as np
from numpy import dot
from numpy.linalg import norm
import pandas as pd
from langchain_openai import OpenAIEmbeddings
from langchain_openai import OpenAI
# .env 파일에서 환경 변수 로드
load_dotenv("/content/.env")
# 환경 변수에서 API 키 가져오기
api_key = os.getenv("OPENAI_API_KEY")
api_key2 = os.getenv("HF_API_KEY")

In [4]:
embeddings = OpenAIEmbeddings(model="text-embedding-ada-002")
query_result = embeddings.embed_query('저는 배가 고파요')
print(query_result)

[-0.016708848997950554, -0.021796436980366707, 0.01521017961204052, -0.02723897434771061, -0.0367831327021122, 0.011857893317937851, -0.034574564546346664, -0.006744012236595154, -0.023912979289889336, -0.016840310767292976, -0.008111219853162766, 0.010871926322579384, -0.010622148402035236, -0.022598357871174812, 0.011240020394325256, -0.00493640685454011, 0.012087952345609665, -0.0028708064928650856, 0.00810464657843113, -0.01610412262380123, 0.001368028810247779, -0.014473991468548775, 0.018207518383860588, -0.012705824337899685, 0.003214251482859254, 0.006418643519282341, 0.00539652444422245, -0.019062023609876633, -0.009215502068400383, -0.0017237984575331211, 0.03449568897485733, -0.01651165634393692, 1.0655629921529908e-05, 0.0030959355644881725, 0.007375031244009733, -0.005560852121561766, -0.006428502965718508, 0.003424591151997447, -0.003828837303444743, -0.0022085653617978096, -0.022480040788650513, -0.010319785214960575, 0.011358336545526981, -0.024662313982844353, 0.01321195438504219, 0.009057747200131416, -0.010622148402035236, -0.025503672659397125, -0.02010057494044304, 0.016485363245010376, 0.014237359166145325, -0.016130415722727776, -0.007828575558960438, -0.017405599355697632, 0.0008183523896150291, 0.02700234204530716, -0.009662473574280739, -0.0007439940236508846, 0.004420417360961437, -0.014132189564406872, 0.00476221926510334, 0.020310914143919945, -0.013724656775593758, 0.011851320043206215, -0.010273773223161697, 0.007835148833692074, 0.022243408486247063, 0.0027524903416633606, -0.023834101855754852, 0.006228023208677769, 0.01793144829571247, 0.04188386723399162, -0.020652716979384422, -0.008814542554318905, 0.03197161480784416, -0.006816316395998001, -0.009846520610153675, 0.00033112047822214663, -0.03168239817023277, 0.014079604297876358, 0.031025085598230362, -0.022322285920381546, 0.001598087721504271, 0.00963618140667677, 0.009070893749594688, 0.011779015883803368, -0.032812971621751785, 0.015170740894973278, -0.034232765436172485, -0.0056923143565654755, 0.005376805085688829, 0.024083880707621574, -0.010898218490183353, 0.03591547906398773, 0.005666022188961506, 0.008834261447191238, -0.01199592836201191, 0.0346534438431263, -0.008531898260116577, -0.018181227147579193, 0.0012250636937096715, -0.005182898137718439, -0.019587872549891472, -0.00926151406019926, -0.030814746394753456, -0.004995564464479685, 0.01974562741816044, 0.008190097287297249, 0.009452134370803833, -0.015091863460838795, 0.014566014520823956, 0.025740304961800575, 0.017970886081457138, -0.03880764916539192, -0.019614163786172867, 0.013225100003182888, -0.0037762525025755167, -0.01585434563457966, -0.008341277949512005, -0.010530124418437481, -0.00212968816049397, 0.0145923076197505, 0.003372006118297577, 0.009386403486132622, 0.008446448482573032, 0.006198443938046694, -0.02316364459693432, -0.03278667852282524, 0.022624649107456207, 0.01468433067202568, 0.05308444797992706, 0.01804976351559162, 0.02947383187711239, -0.01214710995554924, -0.03467973694205284, -0.01774740032851696, -0.015880636870861053, -0.00040814914973452687, -0.0204029381275177, -0.025319624692201614, 0.008893419988453388, 0.023203084245324135, -0.011989355087280273, -0.03391725569963455, 0.02175699919462204, 0.02270352654159069, 0.04564368724822998, 0.006001250818371773, -0.008952577598392963, -0.0001106131385313347, 6.686086999252439e-05, -0.013119930401444435, 0.0174450371414423, -0.004016171209514141, 0.0013877481687813997, 0.011476652696728706, -0.014828938990831375, 0.020389791578054428, -0.0009300952660851181, -0.006096560973674059, 0.013218526728451252, 0.026686832308769226, 0.02045552246272564, -0.027843700721859932, 0.004279095679521561, 0.04148947820067406, -0.0036842289846390486, -0.012166828848421574, -0.01603839173913002, -0.015893783420324326, 0.003914287779480219, 0.012475765310227871, -0.011404348537325859, 0.016169853508472443, -0.023558031767606735, 0.014289944432675838, 0.01999540440738201, -0.00021773431217297912, -0.014605453237891197, 0.003989878576248884, -0.03315477445721626, -0.011036254465579987, 0.011286032386124134, 0.00716469157487154, 0.01199592836201191, -0.008236108347773552, 0.010398662649095058, -0.01639333926141262, 0.016432778909802437, -0.007670821156352758, 0.013790387660264969, 0.030157435685396194, -0.005074441898614168, -0.011187436059117317, -0.618818998336792, -0.012718970887362957, 0.023439714685082436, -0.004620897118002176, 0.028527304530143738, 0.019311800599098206, -0.0010549844009801745, 0.025858620181679726, 0.005416243802756071, 0.01217340212315321, -0.012265426106750965, 0.01940382458269596, 0.0013170872116461396, 0.01350117102265358, 0.014421406202018261, -0.012219414114952087, 0.03226083144545555, -0.005294641479849815, 0.012962175533175468, -0.013842972926795483, -0.032103076577186584, 0.007434188853949308, -0.015302203595638275, 0.014342528767883778, 0.03018372692167759, 0.015052424743771553, 0.011963062919676304, -0.006080128252506256, -0.01927236281335354, 0.053268495947122574, -0.012995040975511074, 0.03633616119623184, -0.009406122379004955, 0.0023679633159190416, 0.041121385991573334, -0.017852570861577988, -0.009248367510735989, 0.02776482328772545, 0.021388905122876167, 0.03791370615363121, -0.012390314601361752, -0.02081046998500824, 0.004223224241286516, -0.006711146794259548, 0.0012891514925286174, 0.009688766673207283, 0.01981135830283165, -0.008656787686049938, -0.0013220170512795448, 0.001133861718699336, -0.018943706527352333, -0.0023466008715331554, -0.0053537990897893906, 0.017550207674503326, -0.003743387060239911, 0.011450360529124737, 0.010707598179578781, -0.025963790714740753, 8.144495950546116e-05, -0.002175699919462204, 0.014566014520823956, 0.0030778595246374607, -0.020376645028591156, -0.0012760052923113108, -0.03189273551106453, 0.01774740032851696, -0.03439052030444145, 0.007085814140737057, -0.0104381013661623, -0.026739416643977165, -0.009484999813139439, -0.028027746826410294, -0.007125252857804298, 0.01574917510151863, 0.03615211322903633, 0.0023055188357830048, 0.025017261505126953, 0.003375292755663395, -0.012771555222570896, -0.00866993423551321, 0.005758045706897974, 0.014158481732010841, -0.01129260566085577, -0.009951691143214703, 0.0005932233179919422, -0.0027229113038629293, -0.030525529757142067, -0.00934696476906538, -0.003579059150069952, -0.0415157712996006, 0.019009437412023544, 0.03331252932548523, 0.0046110376715660095, -0.01258750818669796, -0.009057747200131416, -0.005373518448323011, 0.0027344143018126488, -0.02074473910033703, 0.0170900896191597, -0.006257602013647556, -0.004890394862741232, -0.004423703998327255, 0.01134518999606371, -0.005015283823013306, 0.04622212052345276, -0.00123492325656116, -0.03360174596309662, -0.022611502557992935, 0.0007238638936541975, -0.007749698590487242, 0.027554482221603394, 0.0058073438704013824, 0.00069099833490327, -0.0033490003552287817, 0.03680942580103874, -0.021257441490888596, 4.087653724127449e-05, -0.011286032386124134, 0.009642754681408405, -0.00810464657843113, 0.016143562272191048, -0.014263652265071869, 0.01869392953813076, -0.013067345134913921, -0.01615670882165432, 0.04101621359586716, -0.00443685008212924, -0.01002399530261755, -0.020955080166459084, 0.010622148402035236, -0.01933809369802475, -0.009149771183729172, 0.01382982637733221, -0.016892896965146065, 0.007677393965423107, -0.002427121391519904, 0.025911204516887665, -0.000347758672432974, 0.021507220342755318, -0.02571401186287403, -0.024451974779367447, 0.013869265094399452, -0.0351267084479332, -0.003782825544476509, 0.014184774830937386, -0.0034936086740344763, -0.03170869126915932, -0.016459070146083832, -0.0006630626157857478, 0.022388016805052757, 0.012074805796146393, 0.00403917720541358, -0.0015989093808457255, 0.009708485566079617, 0.01933809369802475, 0.0056988876312971115, 0.02292701229453087, -0.004791798070073128, -0.030525529757142067, 0.011686991900205612, 0.00939954910427332, -0.007802283391356468, -0.012055085971951485, -0.006737439427524805, 0.009734777733683586, -0.05063924938440323, -0.011279459111392498, 0.013803534209728241, -0.01916719228029251, -0.02683144062757492, -0.0038452702574431896, 0.004384265281260014, 0.011568675749003887, -0.025043554604053497, 0.0001987339201150462, 0.0012291718740016222, 0.02092878706753254, -0.007960038259625435, -0.01893056184053421, -0.02535906434059143, 0.0006289646262302995, 0.013540609739720821, -0.014145336113870144, 0.011161142960190773, 0.041305433958768845, 0.012488911859691143, 0.006550105754286051, 0.032865557819604874, -0.02718638814985752, 0.010365796275436878, -0.009544157423079014, 0.022506333887577057, -0.01037894282490015, 0.00048394533223472536, -0.01070102583616972, -0.016932334750890732, -0.010990242473781109, 0.03318106755614281, 0.02576659619808197, 0.023847248405218124, 0.008032342419028282, 0.003240543883293867, 0.015499397180974483, -0.008374144323170185, 0.016669411212205887, -0.03751932084560394, -0.00773655204102397, -0.01406645867973566, 0.011108558624982834, 0.01158182229846716, -0.007795710116624832, -0.023715786635875702, -0.005994677543640137, -0.003100865287706256, 0.03018372692167759, 0.011976209469139576, -0.020310914143919945, 0.009977983310818672, -0.021717559546232224, 0.01435567531734705, -0.00158411986194551, 0.013106783851981163, -0.0014378681080415845, -0.015433665364980698, -0.01011601835489273, 0.0053800917230546474, 0.003238900564610958, 0.027817407622933388, 0.015551981516182423, -0.011693565174937248, -0.025792889297008514, 0.008939431980252266, -0.018601905554533005, 0.04188386723399162, 0.014973548240959644, -0.02547737956047058, 0.004006311297416687, -0.017024358734488487, 0.017182113602757454, 0.00493969302624464, -0.005278208293020725, 0.003018701449036598, 0.005804057233035564, -0.009899105876684189, 0.009780789725482464, 0.029342370107769966, 0.005120453890413046, 0.005081015173345804, -0.03993822634220123, 0.011299178935587406, -0.03780853748321533, -0.006283894646912813, -0.006047262344509363, -0.0019768632482737303, -0.0003502235922496766, -0.038465846329927444, 0.0005077728419564664, 0.011194008402526379, 0.01662997156381607, 0.0192197784781456, 0.008249254897236824, 0.03467973694205284, -0.01438196748495102, 0.016708848997950554, 0.023860394954681396, -0.018891122192144394, -0.001677786698564887, -0.02984192594885826, -0.030104849487543106, 0.0013466662494465709, -0.008157230913639069, -0.03704605624079704, 0.004242943599820137, -0.02292701229453087, 0.0017122955759987235, -0.013540609739720821, 0.01603839173913002, -0.017905155196785927, 0.021901607513427734, -0.023689493536949158, -0.0036349305883049965, -0.04004339501261711, 0.00828212033957243, 0.019088314846158028, 0.00911033246666193, -0.0298945102840662, -0.029684171080589294, 0.006523813121020794, -0.03341769799590111, 0.032339707016944885, -0.008729091845452785, 0.01344201248139143, -0.010122591629624367, 0.011194008402526379, -0.047010891139507294, -0.025188162922859192, 0.028264379128813744, 0.004466429352760315, 0.010825914330780506, -0.024097027257084846, 0.0017155820969492197, -0.013369708321988583, -0.003625070909038186, -0.013934995979070663, 0.012160256505012512, 0.0031879590824246407, -0.0014271867694333196, -0.005090874619781971, 0.01028691977262497, -0.017287282273173332, -0.018601905554533005, -0.005708747077733278, -0.018825391307473183, -0.01986394263803959, -0.020061135292053223, -0.009018308483064175, -0.011299178935587406, -0.03141947090625763, 0.024189049378037453, 0.01686660386621952, -0.008466167375445366, 0.015302203595638275, -0.011923624202609062, -0.0016728568589314818, 0.056213248521089554, -0.03278667852282524, 0.016761433333158493, -0.013488024473190308, 0.014934109523892403, 0.015131302177906036, -0.02529333345592022, -0.007670821156352758, 0.003743387060239911, -0.0029348942916840315, 0.022953305393457413, -0.005120453890413046, 0.013606340624392033, 0.005547706037759781, 0.013363135978579521, 0.0007793245022185147, -0.011890758760273457, -0.036704253405332565, 0.03365433216094971, -0.019601019099354744, -0.011200581677258015, -0.010530124418437481, 0.01521017961204052, 0.023978710174560547, 0.008236108347773552, 0.012502058409154415, 0.015012986958026886, -0.00021629645198117942, 0.04120026156306267, -0.014631746336817741, -0.007368457969278097, -0.009182636626064777, -0.009360110387206078, -0.009471853263676167, 0.0070989602245390415, 0.03331252932548523, 0.005212477408349514, 0.0007423507631756365, -0.000821228080894798, 0.029552709311246872, 0.015275911428034306, 0.021559804677963257, 0.014828938990831375, -0.005409670528024435, 0.0008372500888071954, -0.015657151117920876, 0.00037055916618555784, 0.011351763270795345, -0.01085220742970705, -0.013948142528533936, 0.04793112725019455, 0.009169490076601505, -0.0265816617757082, -0.004246229771524668, 0.02134946547448635, -0.002450127387419343, 0.007283007260411978, 0.017970886081457138, 0.01087849959731102, 0.0009358467650599778, 0.007683967240154743, -0.01840471290051937, 0.003210964845493436, -0.010766756720840931, -0.01840471290051937, -0.014513430185616016, -0.035415925085544586, -0.008499032817780972, -0.022427456453442574, -0.00972820445895195, -0.025096138939261436, -0.008604202419519424, -0.031051378697156906, -0.04196274280548096, -0.00603082962334156, 0.0104381013661623, 0.03215566277503967, -0.023781517520546913, -0.01828639581799507, 0.004801657982170582, -0.005715320352464914, -0.023571178317070007, 0.01253492385149002, 0.001469090348109603, -0.014053312130272388, 0.026792002841830254, 0.00937325693666935, -0.01927236281335354, 0.0006856576655991375, -0.00851875264197588, 0.02329510636627674, 0.013356562703847885, 0.012357449159026146, -0.004864102229475975, -0.0008327310788445175, 0.00035720752202905715, 0.0036513633094727993, 0.0099648367613554, -0.007513066288083792, 0.013192234560847282, 0.020140012726187706, -0.028579888865351677, 0.003127157688140869, -0.02405758760869503, 0.006070268340408802, 0.013606340624392033, 0.014395114034414291, 0.009274660609662533, -0.020718447864055634, 0.016248730942606926, 0.02311106026172638, -0.010260626673698425, 0.006714433431625366, -0.019679896533489227, 0.029026860371232033, 0.02512243203818798, -0.01850988157093525, 0.01485523208975792, -0.014250505715608597, 0.015341642312705517, -0.011134850792586803, -0.01975877210497856, 0.02913202904164791, 0.031866442412137985, -0.004213364329189062, 0.004890394862741232, -0.013244819827377796, -0.024307366460561752, -0.023203084245324135, -0.011483225971460342, 0.0012447829358279705, 0.015118156559765339, -0.022006776183843613, -0.014289944432675838, -0.007171264383941889, -0.0077562713995575905, 0.0006219806964509189, 0.00012612158025149256, 2.100314486597199e-05, -0.03278667852282524, -0.01597266085445881, 0.003352286759763956, -0.009511291980743408, -0.009156344458460808, -0.00937325693666935, -0.024570289999246597, -0.014434552751481533, -0.00869622640311718, -0.007519639562815428, 0.01674828864634037, 0.008032342419028282, 0.006730866152793169, 0.00314687704667449, 0.000882440188433975, 0.005370231810957193, -0.02647649310529232, -0.0049561262130737305, 0.013908703811466694, 0.053215909749269485, 0.016485363245010376, 0.02612154558300972, 0.018325835466384888, 0.020258329808712006, 0.011009961366653442, 0.0023926126305013895, -0.0070135099813342094, -0.021664975211024284, 0.007775990758091211, -0.032050490379333496, 0.026568517088890076, -0.00014399221981875598, 0.02140205167233944, 0.03649391606450081, 0.027738530188798904, 0.00185690401121974, 0.03226083144545555, -0.006809743586927652, -0.004946266300976276, -0.02546423301100731, 0.012331156991422176, 0.006277321372181177, -0.025621987879276276, 0.010162030346691608, -0.02612154558300972, 0.011450360529124737, -0.018141787499189377, 0.007486774120479822, -0.020258329808712006, 0.016603680327534676, -0.017142673954367638, 0.03241858631372452, -0.054688286036252975, 0.004561739508062601, 0.02512243203818798, 0.011088838800787926, 0.0023038755171000957, -0.0183915663510561, 0.011838173493742943, -0.01359319407492876, 0.00657639792189002, 0.025976937264204025, 0.007289580535143614, -0.02216453105211258, 7.235557859530672e-05, -0.004417130723595619, 0.019837649539113045, -0.026673685759305954, -0.018483588472008705, 0.0101423105224967, -0.014907816424965858, -0.01833898015320301, -0.015893783420324326, -0.028790228068828583, -0.045485932379961014, 0.017852570861577988, 0.0028691631741821766, -0.01603839173913002, 0.02353173866868019, 0.007545931730419397, -0.018299542367458344, -0.0101423105224967, 0.030210020020604134, 0.0034771759528666735, 0.011805308051407337, 0.04091104492545128, 0.02842213399708271, -0.0035724861081689596, -0.0219410452991724, 0.013198807835578918, 0.010037140920758247, -0.014171628281474113, -0.013908703811466694, 0.026923464611172676, -0.012567789293825626, -0.02033720724284649, 0.0008750454871915281, -0.00046217188355512917, 0.004555166233330965, 0.0012875081738457084, 0.03312848135828972, -0.006658561993390322, 0.0013639206299558282, 0.010194895789027214, -0.005859928671270609, -0.0149472551420331, 0.04162093997001648, -0.00825582817196846, -0.0015101723838597536, -0.012186548672616482, -0.03680942580103874, -0.00565944891422987, -0.00664541544392705, -0.010109445080161095, 0.0282380860298872, 0.021967338398098946, -0.020586984232068062, -0.004239656962454319, -0.00026354068540968, -0.007381604053080082, 0.010247481055557728, -0.014316236600279808, 0.03273409605026245, -0.005679168272763491, 0.003782825544476509, 0.00587964802980423, 0.005015283823013306, 0.003920861054211855, 0.005554279312491417, 0.002430408028885722, 0.03730897977948189, -0.004801657982170582, 0.00955073069781065, -0.00734216533601284, 0.03901799023151398, 0.013764095492661, 0.0017780266935005784, -0.005297927651554346, -0.006523813121020794, -0.0023646769113838673, -0.009866240434348583, -0.009892532601952553, -0.005682454910129309, -0.020087428390979767, -0.006691427435725927, -0.03730897977948189, 0.0004625827132258564, -0.02630559168756008, 0.011167716234922409, 0.012331156991422176, 0.04075329005718231, -0.011825027875602245, -0.01916719228029251, -0.013790387660264969, 0.02547737956047058, -0.014132189564406872, -0.023912979289889336, -0.0018174652941524982, 0.0028905258513987064, -0.014658038504421711, 0.013948142528533936, -0.008992016315460205, 0.00970191229134798, -0.012055085971951485, 0.007513066288083792, 0.01308706495910883, -0.0068951938301324844, 0.019298655912280083, -0.008209816180169582, -0.0003356394881848246, -0.016971774399280548, -0.011522664688527584, -0.00038801899063400924, 0.011259740218520164, -0.0006293753976933658, 0.017786839976906776, 0.00792717281728983, 0.013139649294316769, -0.019837649539113045, -0.010280346497893333, -0.006070268340408802, 0.014802646823227406, 0.026897171512246132, 0.028685057535767555, -0.02506984770298004, -0.03683571517467499, -0.0022102086804807186, -0.006320046726614237, -0.016406485810875893, -0.036467622965574265, -0.01406645867973566, 0.0006149967666715384, 0.020376645028591156, -0.002468203427270055, -0.027081219479441643, 0.02163868211209774, -0.01751076802611351, -0.028080331161618233, 0.00561672355979681, 0.009596742689609528, 0.004515727516263723, 0.0030071984510868788, 0.03373320773243904, -0.003483748994767666, 0.004246229771524668, -0.010470966808497906, 0.005212477408349514, -0.003291485598310828, -0.016932334750890732, -0.0003793917712755501, 0.006592830643057823, -0.02729155868291855, 0.03360174596309662, 0.006070268340408802, -0.024662313982844353, -0.01981135830283165, 0.008505606092512608, -0.029500124976038933, 0.0015455028042197227, 0.01732672192156315, 0.01547310408204794, 0.0050415764562785625, -0.005370231810957193, 0.0058960807509720325, 0.026371322572231293, -0.008413583040237427, 0.00661912327632308, -0.006849182303994894, -0.021651828661561012, -0.005784337874501944, -0.007618236355483532, -0.00385512993671, -0.027975162491202354, -0.02217767760157585, -0.012942456640303135, 0.013146222569048405, -0.0019144186517223716, 0.018969999626278877, 

In [5]:
# <오픈AI 임베딩을 활용한 문장들 간 코사인 유사도 계산>

data = [
    '주식 시장이 급등했어요',
    '시장 물가가 올랐어요',
    '전통 시장에는 다양한 물품들을 팔아요',
    '부동산 시장이 점점 더 복잡해지고 있어요',
    '저는 빠른 비트를 좋아해요',
    '최근 비트코인 가격이 많이 변동했어요',
]
df = pd.DataFrame(data, columns=['text'])
df

                     text
0            주식 시장이 급등했어요
1             시장 물가가 올랐어요
2    전통 시장에는 다양한 물품들을 팔아요
3  부동산 시장이 점점 더 복잡해지고 있어요
4          저는 빠른 비트를 좋아해요
5    최근 비트코인 가격이 많이 변동했어요

In [6]:
# 텍스트를 임베딩 벡터로 변환하는 함수 정의
def get_embedding(text):
  return embeddings.embed_query(text)

# DataFrame의 각 행에 대해 'text' 열의 내용을 임베딩 벡터로 변환
df['embedding'] = df.apply(lambda row: get_embedding(
        row.text,
    ), axis=1)

# 변환된 DataFrame 출력
df

                     text                                          embedding
0            주식 시장이 급등했어요  [-0.01370231993496418, -0.035045821219682693, ...
1             시장 물가가 올랐어요  [-0.00015702718519605696, -0.03539642691612243...
2    전통 시장에는 다양한 물품들을 팔아요  [-0.009272306226193905, -0.01461657416075468, ...
3  부동산 시장이 점점 더 복잡해지고 있어요  [-0.017441052943468094, -0.0031565295066684484...
4          저는 빠른 비트를 좋아해요  [-0.03796839341521263, -0.013386794365942478, ...
5    최근 비트코인 가격이 많이 변동했어요  [-0.01749446988105774, -0.021561449393630028, ...

In [7]:
# 코사인 유사도 계산 함수
def cos_sim(A, B):
    return dot(A, B)/(norm(A)*norm(B))

# 주어진 쿼리와 가장 유사한 상위 3개의 문서를 반환하는 함수
def return_answer_candidate(df, query):
    # 쿼리 텍스트를 임베딩 벡터로 변환
    query_embedding = get_embedding(query)

    # DataFrame의 각 문서 임베딩과 쿼리 임베딩 간의 유사도 계산
    df["similarity"] = df.embedding.apply(lambda x: cos_sim(np.array(x), np.array(query_embedding)))

    # 유사도가 높은 순으로 정렬하고 상위 3개 문서 선택
    top_three_doc = df.sort_values("similarity", ascending=False).head(3)

    return top_three_doc

# 예시 쿼리로 유사한 문서 검색
sim_result = return_answer_candidate(df, '과일 값이 비싸다.')
sim_result

,text,embedding,similarity
2,전통 시장에는 다양한 물품들을 팔아요,"[-0.009272306226193905, -0.01461657416075468, ...",0.824548
1,시장 물가가 올랐어요,"[-0.00015702718519605696, -0.03539642691612243...",0.814571
0,주식 시장이 급등했어요,"[-0.01370231993496418, -0.035045821219682693, ...",0.805389

In [10]:
# <BGE-M3 임베딩을 활용한 문장들 간 코사인 유사도 계산>

# 라이브러리 불러오기
# from langchain.embeddings import HuggingFaceBgeEmbeddings
from langchain_huggingface import HuggingFaceEmbeddings

# BGE-M3 모델 초기화
embeddings = HuggingFaceEmbeddings(model_name='BAAI/bge-m3')

# 데이터셋 생성
data = [
    '주식 시장이 급등했어요',
    '시장 물가가 올랐어요',
    '전통 시장에는 다양한 물품들을 팔아요',
    '부동산 시장이 점점 더 복잡해지고 있어요',
    '저는 빠른 비트를 좋아해요',
    '최근 비트코인 가격이 많이 변동했어요',
]
df = pd.DataFrame(data, columns=['text'])

# DataFrame의 각 행을 벡터로 변환
df['embedding'] = df['text'].apply(get_embedding)
df

ValueError: Due to a serious vulnerability issue in `torch.load`, even with `weights_only=True`, we now require users to upgrade torch to at least v2.6 in order to use the function. This version restriction does not apply when loading files with safetensors.
See the vulnerability report here https://nvd.nist.gov/vuln/detail/CVE-2025-32434

In [ ]:
# 쿼리 예시로 유사 문서 검색
sim_result = return_answer_candidate(df, '과일 값이 비싸다')
sim_result